# Generated by Django 5.2.17 on 2026-09-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seed_demo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.TextField(blank=True),
        ),
    ]
