# Generated by Django 5.2.17 on 2026-09-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(choices=[('highlight', 'Highlight'), ('note', 'Sticky Note'), ('underline', 'Underline')], default='highlight', max_length=50)),
                ('color', models.CharField(default='#ffeb3b', max_length=50)),
                ('rects', models.JSONField(blank=True, default=list)),
                ('selected_text', models.TextField(blank=True, default='')),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'annotations',
                'ordering': ['page_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('short_title', models.CharField(blank=True, default='', max_length=255)),
                ('item_type', models.CharField(default='journalArticle', max_length=100)),
                ('repository', models.CharField(blank=True, default='', max_length=255)),
                ('archive_id', models.CharField(blank=True, default='', max_length=100)),
                ('doi', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='English', max_length=50)),
                ('license', models.CharField(blank=True, default='', max_length=100)),
                ('version', models.CharField(blank=True, default='1.0', max_length=50)),
                ('citation_key', models.CharField(blank=True, default='', max_length=100)),
                ('loc_in_archive', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('rag_status', models.CharField(choices=[('PENDING', 'Pending Ingestion'), ('INDEXING', 'Indexing in Progress'), ('INDEXED', 'Indexed Successfully'), ('FAILED', 'Indexing Failed')], default='PENDING', max_length=50)),
                ('extra', models.TextField(blank=True, default='')),
                ('in_trash', models.BooleanField(default=False)),
                ('is_publication', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('last_read', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'document_authors',
                'ordering': ['author_order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'document_collections',
            },
        ),
        migrations.CreateModel(
            name='DocumentDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'document_domains',
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW', 'View Only'), ('COMMENT', 'Comment / Annotate'), ('EDIT', 'Full Edit')], default='VIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_shares',
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'document_tags',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'domains',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'related_documents',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
    ]
