# Generated by Django 5.2.17 on 2026-09-17 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections_app', '0002_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='primary_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_documents', to='collections_app.collection'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.author'),
        ),
        migrations.AddField(
            model_name='documentauthor',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='authors',
            field=models.ManyToManyField(related_name='documents', through='documents.DocumentAuthor', to='documents.author'),
        ),
        migrations.AddField(
            model_name='documentcollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collections_app.collection'),
        ),
        migrations.AddField(
            model_name='documentcollection',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='collections',
            field=models.ManyToManyField(related_name='documents', through='documents.DocumentCollection', to='collections_app.collection'),
        ),
        migrations.AddField(
            model_name='documentdomain',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='shared_with_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttag',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentdomain',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.domain'),
        ),
        migrations.AddField(
            model_name='document',
            name='domains',
            field=models.ManyToManyField(related_name='documents', through='documents.DocumentDomain', to='documents.domain'),
        ),
        migrations.AddField(
            model_name='note',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='documents.document'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relateddocument',
            name='document_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='documents.document'),
        ),
        migrations.AddField(
            model_name='relateddocument',
            name='document_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documenttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.tag'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(related_name='documents', through='documents.DocumentTag', to='documents.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='documentauthor',
            unique_together={('document', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='documentcollection',
            unique_together={('document', 'collection')},
        ),
        migrations.AlterUniqueTogether(
            name='documentshare',
            unique_together={('document', 'shared_with_user')},
        ),
        migrations.AlterUniqueTogether(
            name='documentdomain',
            unique_together={('document', 'domain')},
        ),
        migrations.AlterUniqueTogether(
            name='relateddocument',
            unique_together={('document_1', 'document_2')},
        ),
        migrations.AlterUniqueTogether(
            name='documenttag',
            unique_together={('document', 'tag')},
        ),
    ]
