CREATE TYPE "rag_status" AS ENUM (
  'PENDING',
  'INDEXING',
  'INDEXED',
  'FAILED'
);

CREATE TYPE "annotation_type" AS ENUM (
  'highlight',
  'note',
  'underline'
);

CREATE TYPE "share_permission" AS ENUM (
  'VIEW',
  'COMMENT',
  'EDIT'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "password" varchar(128) NOT NULL,
  "last_login" timestamp with time zone,
  "username" text NOT NULL,
  "email" varchar(254) UNIQUE NOT NULL,
  "avatar" varchar(100) DEFAULT '',
  "institution" text DEFAULT '',
  "is_active" boolean NOT NULL
);

CREATE TABLE "authors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(150) DEFAULT '',
  "last_name" varchar(150)
);

CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "domains" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) UNIQUE NOT NULL
);

CREATE TABLE "documents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" integer NOT NULL,
  "primary_collection_id" integer,
  "title" varchar(500) NOT NULL,
  "short_title" varchar(255) DEFAULT '',
  "item_type" varchar(100) DEFAULT 'journalArticle',
  "repository" varchar(255) DEFAULT '',
  "archive_id" varchar(100) DEFAULT '',
  "doi" varchar(255) DEFAULT '',
  "url" varchar(1000) DEFAULT '',
  "genre" varchar(100) DEFAULT '',
  "date" timestamp with time zone,
  "language" varchar(50) DEFAULT 'English',
  "license" varchar(100) DEFAULT '',
  "version" varchar(50) DEFAULT '1.0',
  "citation_key" varchar(100) DEFAULT '',
  "loc_in_archive" varchar(255) DEFAULT '',
  "file" varchar(255),
  "file_size" bigint,
  "rag_status" rag_status DEFAULT 'PENDING',
  "extra" text DEFAULT '',
  "in_trash" boolean DEFAULT false,
  "is_publication" boolean DEFAULT false,
  "is_duplicate" boolean DEFAULT false,
  "last_read" timestamp with time zone,
  "date_added" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "date_modified" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "document_authors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "author_id" integer NOT NULL,
  "author_order" integer DEFAULT 1
);

CREATE TABLE "document_tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "tag_id" integer NOT NULL
);

CREATE TABLE "document_domains" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "domain_id" integer NOT NULL
);

CREATE TABLE "document_collections" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "collection_id" integer NOT NULL
);

CREATE TABLE "annotations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "page_number" integer DEFAULT 1,
  "type" annotation_type DEFAULT 'highlight',
  "color" varchar(50) DEFAULT '#ffeb3b',
  "rects" jsonb,
  "selected_text" text DEFAULT '',
  "comment" text DEFAULT '',
  "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "notes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "document_id" integer,
  "title" varchar(255) NOT NULL,
  "content" text DEFAULT '',
  "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "document_shares" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "shared_with_user_id" integer NOT NULL,
  "permission" share_permission DEFAULT 'VIEW',
  "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "related_documents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_1_id" integer NOT NULL,
  "document_2_id" integer NOT NULL,
  "relation_type" varchar(50) DEFAULT 'manual',
  "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "collection_shares" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "collection_id" integer NOT NULL,
  "shared_with_user_id" integer NOT NULL,
  "permission" share_permission DEFAULT 'VIEW',
  "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ON "document_authors" ("document_id", "author_id");
CREATE UNIQUE INDEX ON "document_tags" ("document_id", "tag_id");
CREATE UNIQUE INDEX ON "document_domains" ("document_id", "domain_id");
CREATE UNIQUE INDEX ON "document_collections" ("document_id", "collection_id");
CREATE UNIQUE INDEX ON "document_shares" ("document_id", "shared_with_user_id");
CREATE UNIQUE INDEX ON "related_documents" ("document_1_id", "document_2_id");
CREATE UNIQUE INDEX ON "collection_shares" ("collection_id", "shared_with_user_id");

COMMENT ON COLUMN "documents"."doi" IS 'Indexed';

ALTER TABLE "documents" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "documents" ADD FOREIGN KEY ("primary_collection_id") REFERENCES "collection_shares" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "document_authors" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "document_authors" ADD FOREIGN KEY ("author_id") REFERENCES "authors" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "document_tags" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "document_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "document_domains" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "document_domains" ADD FOREIGN KEY ("domain_id") REFERENCES "domains" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "document_collections" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "document_collections" ADD FOREIGN KEY ("collection_id") REFERENCES "collection_shares" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "annotations" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "annotations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "notes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "notes" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "document_shares" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "document_shares" ADD FOREIGN KEY ("shared_with_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "related_documents" ADD FOREIGN KEY ("document_1_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "related_documents" ADD FOREIGN KEY ("document_2_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;