CREATE TABLE "documents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "short_title" varchar,
  "item_type" varchar,
  "repository" varchar,
  "archive_id" varchar,
  "doi" varchar,
  "url" varchar,
  "genre" varchar,
  "date" timestamp,
  "language" varchar,
  "license" varchar,
  "version" varchar,
  "citation_key" varchar,
  "loc_in_archive" varchar,
  "date_added" timestamp,
  "extra" varchar,
  "date_modified" timestamp
);

CREATE TABLE "authors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar
);

CREATE TABLE "document_authors" (
  "document_id" integer NOT NULL,
  "author_id" integer NOT NULL,
  "author_order" integer NOT NULL,
  PRIMARY KEY ("document_id", "author_id")
);

CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "document_tags" (
  "document_id" integer NOT NULL,
  "tag_id" integer NOT NULL,
  PRIMARY KEY ("document_id", "tag_id")
);

CREATE TABLE "domains" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "document_domains" (
  "document_id" integer NOT NULL,
  "domain_id" integer NOT NULL,
  PRIMARY KEY ("document_id", "domain_id")
);

CREATE TABLE "document_groups" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "color" varchar
);

CREATE TABLE "document_group_members" (
  "document_id" integer NOT NULL,
  "group_id" integer NOT NULL,
  PRIMARY KEY ("document_id", "group_id")
);

ALTER TABLE "document_authors" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_authors" ADD FOREIGN KEY ("author_id") REFERENCES "authors" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_tags" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_domains" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_domains" ADD FOREIGN KEY ("domain_id") REFERENCES "domains" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_group_members" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document_group_members" ADD FOREIGN KEY ("group_id") REFERENCES "document_groups" ("id") DEFERRABLE INITIALLY IMMEDIATE;
